package com.example.springbootdemo.bean;

public class Comm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm.cuser
     *
     * @mbg.generated
     */
    private String cuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    public Comm(Integer id, String cname, String cuser, String content) {
        this.id = id;
        this.cname = cname;
        this.cuser = cuser;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm.id
     *
     * @return the value of comm.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm.cname
     *
     * @return the value of comm.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm.cuser
     *
     * @return the value of comm.cuser
     *
     * @mbg.generated
     */
    public String getCuser() {
        return cuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm.content
     *
     * @return the value of comm.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }
}