package com.example.springbootdemo.bean;

import java.util.ArrayList;
import java.util.List;

public class GoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goods
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public GoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGnameIsNull() {
            addCriterion("gname is null");
            return (Criteria) this;
        }

        public Criteria andGnameIsNotNull() {
            addCriterion("gname is not null");
            return (Criteria) this;
        }

        public Criteria andGnameEqualTo(String value) {
            addCriterion("gname =", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotEqualTo(String value) {
            addCriterion("gname <>", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameGreaterThan(String value) {
            addCriterion("gname >", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameGreaterThanOrEqualTo(String value) {
            addCriterion("gname >=", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLessThan(String value) {
            addCriterion("gname <", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLessThanOrEqualTo(String value) {
            addCriterion("gname <=", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameLike(String value) {
            addCriterion("gname like", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotLike(String value) {
            addCriterion("gname not like", value, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameIn(List<String> values) {
            addCriterion("gname in", values, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotIn(List<String> values) {
            addCriterion("gname not in", values, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameBetween(String value1, String value2) {
            addCriterion("gname between", value1, value2, "gname");
            return (Criteria) this;
        }

        public Criteria andGnameNotBetween(String value1, String value2) {
            addCriterion("gname not between", value1, value2, "gname");
            return (Criteria) this;
        }

        public Criteria andGpriceIsNull() {
            addCriterion("gprice is null");
            return (Criteria) this;
        }

        public Criteria andGpriceIsNotNull() {
            addCriterion("gprice is not null");
            return (Criteria) this;
        }

        public Criteria andGpriceEqualTo(String value) {
            addCriterion("gprice =", value, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceNotEqualTo(String value) {
            addCriterion("gprice <>", value, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceGreaterThan(String value) {
            addCriterion("gprice >", value, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceGreaterThanOrEqualTo(String value) {
            addCriterion("gprice >=", value, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceLessThan(String value) {
            addCriterion("gprice <", value, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceLessThanOrEqualTo(String value) {
            addCriterion("gprice <=", value, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceLike(String value) {
            addCriterion("gprice like", value, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceNotLike(String value) {
            addCriterion("gprice not like", value, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceIn(List<String> values) {
            addCriterion("gprice in", values, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceNotIn(List<String> values) {
            addCriterion("gprice not in", values, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceBetween(String value1, String value2) {
            addCriterion("gprice between", value1, value2, "gprice");
            return (Criteria) this;
        }

        public Criteria andGpriceNotBetween(String value1, String value2) {
            addCriterion("gprice not between", value1, value2, "gprice");
            return (Criteria) this;
        }

        public Criteria andGnumberIsNull() {
            addCriterion("gnumber is null");
            return (Criteria) this;
        }

        public Criteria andGnumberIsNotNull() {
            addCriterion("gnumber is not null");
            return (Criteria) this;
        }

        public Criteria andGnumberEqualTo(String value) {
            addCriterion("gnumber =", value, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberNotEqualTo(String value) {
            addCriterion("gnumber <>", value, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberGreaterThan(String value) {
            addCriterion("gnumber >", value, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberGreaterThanOrEqualTo(String value) {
            addCriterion("gnumber >=", value, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberLessThan(String value) {
            addCriterion("gnumber <", value, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberLessThanOrEqualTo(String value) {
            addCriterion("gnumber <=", value, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberLike(String value) {
            addCriterion("gnumber like", value, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberNotLike(String value) {
            addCriterion("gnumber not like", value, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberIn(List<String> values) {
            addCriterion("gnumber in", values, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberNotIn(List<String> values) {
            addCriterion("gnumber not in", values, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberBetween(String value1, String value2) {
            addCriterion("gnumber between", value1, value2, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGnumberNotBetween(String value1, String value2) {
            addCriterion("gnumber not between", value1, value2, "gnumber");
            return (Criteria) this;
        }

        public Criteria andGuserIsNull() {
            addCriterion("guser is null");
            return (Criteria) this;
        }

        public Criteria andGuserIsNotNull() {
            addCriterion("guser is not null");
            return (Criteria) this;
        }

        public Criteria andGuserEqualTo(String value) {
            addCriterion("guser =", value, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserNotEqualTo(String value) {
            addCriterion("guser <>", value, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserGreaterThan(String value) {
            addCriterion("guser >", value, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserGreaterThanOrEqualTo(String value) {
            addCriterion("guser >=", value, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserLessThan(String value) {
            addCriterion("guser <", value, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserLessThanOrEqualTo(String value) {
            addCriterion("guser <=", value, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserLike(String value) {
            addCriterion("guser like", value, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserNotLike(String value) {
            addCriterion("guser not like", value, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserIn(List<String> values) {
            addCriterion("guser in", values, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserNotIn(List<String> values) {
            addCriterion("guser not in", values, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserBetween(String value1, String value2) {
            addCriterion("guser between", value1, value2, "guser");
            return (Criteria) this;
        }

        public Criteria andGuserNotBetween(String value1, String value2) {
            addCriterion("guser not between", value1, value2, "guser");
            return (Criteria) this;
        }

        public Criteria andGphotoIsNull() {
            addCriterion("gphoto is null");
            return (Criteria) this;
        }

        public Criteria andGphotoIsNotNull() {
            addCriterion("gphoto is not null");
            return (Criteria) this;
        }

        public Criteria andGphotoEqualTo(String value) {
            addCriterion("gphoto =", value, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoNotEqualTo(String value) {
            addCriterion("gphoto <>", value, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoGreaterThan(String value) {
            addCriterion("gphoto >", value, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoGreaterThanOrEqualTo(String value) {
            addCriterion("gphoto >=", value, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoLessThan(String value) {
            addCriterion("gphoto <", value, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoLessThanOrEqualTo(String value) {
            addCriterion("gphoto <=", value, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoLike(String value) {
            addCriterion("gphoto like", value, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoNotLike(String value) {
            addCriterion("gphoto not like", value, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoIn(List<String> values) {
            addCriterion("gphoto in", values, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoNotIn(List<String> values) {
            addCriterion("gphoto not in", values, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoBetween(String value1, String value2) {
            addCriterion("gphoto between", value1, value2, "gphoto");
            return (Criteria) this;
        }

        public Criteria andGphotoNotBetween(String value1, String value2) {
            addCriterion("gphoto not between", value1, value2, "gphoto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}