package com.example.springbootdemo.bean;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.onum
     *
     * @mbg.generated
     */
    private String onum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oname
     *
     * @mbg.generated
     */
    private String oname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oprice
     *
     * @mbg.generated
     */
    private String oprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.onumber
     *
     * @mbg.generated
     */
    private String onumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.ouser
     *
     * @mbg.generated
     */
    private String ouser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.oaddress
     *
     * @mbg.generated
     */
    private String oaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    public Order(Integer id, String onum, String oname, String oprice, String onumber, String ouser, String oaddress) {
        this.id = id;
        this.onum = onum;
        this.oname = oname;
        this.oprice = oprice;
        this.onumber = onumber;
        this.ouser = ouser;
        this.oaddress = oaddress;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.onum
     *
     * @return the value of order.onum
     *
     * @mbg.generated
     */
    public String getOnum() {
        return onum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oname
     *
     * @return the value of order.oname
     *
     * @mbg.generated
     */
    public String getOname() {
        return oname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oprice
     *
     * @return the value of order.oprice
     *
     * @mbg.generated
     */
    public String getOprice() {
        return oprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.onumber
     *
     * @return the value of order.onumber
     *
     * @mbg.generated
     */
    public String getOnumber() {
        return onumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.ouser
     *
     * @return the value of order.ouser
     *
     * @mbg.generated
     */
    public String getOuser() {
        return ouser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.oaddress
     *
     * @return the value of order.oaddress
     *
     * @mbg.generated
     */
    public String getOaddress() {
        return oaddress;
    }
}