package com.example.springbootdemo.bean;

public class Vuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuser.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuser.user
     *
     * @mbg.generated
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vuser.pass
     *
     * @mbg.generated
     */
    private String pass;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    public Vuser(Integer id, String user, String pass) {
        this.id = id;
        this.user = user;
        this.pass = pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuser.id
     *
     * @return the value of vuser.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuser.user
     *
     * @return the value of vuser.user
     *
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vuser.pass
     *
     * @return the value of vuser.pass
     *
     * @mbg.generated
     */
    public String getPass() {
        return pass;
    }
}