package com.example.springbootdemo.dao;

import com.example.springbootdemo.bean.Comm;
import com.example.springbootdemo.bean.CommExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface CommMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    long countByExample(CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    int deleteByExample(CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    @Delete({
        "delete from comm",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    @Insert({
        "insert into comm (id, cname, ",
        "cuser, content)",
        "values (#{id,jdbcType=INTEGER}, #{cname,jdbcType=VARCHAR}, ",
        "#{cuser,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR})"
    })
    int insert(Comm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    int insertSelective(Comm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    List<Comm> selectByExample(CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, cname, cuser, content",
        "from comm",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.springbootdemo.dao.CommMapper.BaseResultMap")
    Comm selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Comm record, @Param("example") CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Comm record, @Param("example") CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Comm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm
     *
     * @mbg.generated
     */
    @Update({
        "update comm",
        "set cname = #{cname,jdbcType=VARCHAR},",
          "cuser = #{cuser,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Comm record);
}