package com.example.springbootdemo.dao;

import com.example.springbootdemo.bean.Order;
import com.example.springbootdemo.bean.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Delete({
        "delete from order",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Insert({
        "insert into order (id, onum, ",
        "oname, oprice, onumber, ",
        "ouser, oaddress)",
        "values (#{id,jdbcType=INTEGER}, #{onum,jdbcType=VARCHAR}, ",
        "#{oname,jdbcType=VARCHAR}, #{oprice,jdbcType=VARCHAR}, #{onumber,jdbcType=VARCHAR}, ",
        "#{ouser,jdbcType=VARCHAR}, #{oaddress,jdbcType=VARCHAR})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, onum, oname, oprice, onumber, ouser, oaddress",
        "from order",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.springbootdemo.dao.OrderMapper.BaseResultMap")
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Update({
        "update order",
        "set onum = #{onum,jdbcType=VARCHAR},",
          "oname = #{oname,jdbcType=VARCHAR},",
          "oprice = #{oprice,jdbcType=VARCHAR},",
          "onumber = #{onumber,jdbcType=VARCHAR},",
          "ouser = #{ouser,jdbcType=VARCHAR},",
          "oaddress = #{oaddress,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Order record);
}