package com.example.springbootdemo.dao;

import com.example.springbootdemo.bean.Vuser;
import com.example.springbootdemo.bean.VuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;

public interface VuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    long countByExample(VuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    int deleteByExample(VuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    @Delete({
        "delete from vuser",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    @Insert({
        "insert into vuser (user, pass)",
        "values (#{user,jdbcType=VARCHAR}, #{pass,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Vuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    int insertSelective(Vuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    List<Vuser> selectByExample(VuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, user, pass",
        "from vuser",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.example.springbootdemo.dao.VuserMapper.BaseResultMap")
    Vuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Vuser record, @Param("example") VuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Vuser record, @Param("example") VuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Vuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vuser
     *
     * @mbg.generated
     */
    @Update({
        "update vuser",
        "set user = #{user,jdbcType=VARCHAR},",
          "pass = #{pass,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Vuser record);
}